datasources:
  postgres:
    # url: jdbc:postgresql://postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    # username: added in secret
    # password: added in secret
kestra:
  server:
    basic-auth:
      enabled: false
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/
